### ISSUE TITLE
Omemo certs sending 

### ISSUE THREAD

**Issue by danjde** [wstrm/omemo-utils#2]
Hi Devs, (and excuse me if we should have the wrong place),
we are an Italian association and we have implemented our own Jabber/XMPP service,
we would like to understand better how the client send each certificates.
in particular we wonder if these OMEMO certificates passing through the server can somehow be intercepted.

in case we have the wrong place for this question, could you kindly point us to the most relevant project to this theme?

Thanks!

EXIT

**Comment by jubalh** [comment]
> we would like to understand better how the client send each certificates

Did you read https://xmpp.org/extensions/xep-0384.html and https://xmpp.org/extensions/inbox/omemo-media-sharing.html already?

**Comment by jubalh** [comment]
@danjde still relevant?

**Comment by danjde** [comment]
Thanks @jubalh,
I was hoping for a simpler explanation but something I understood ;-P
